name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome to your first contribution to the repository! It appears you have opened a new issue, and we are working on it."
        pr-message: "Welcome to your first pull request! We'll review it and see if it meets our repository's goals, and more."
